name: shorebird_code_push_api_client

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - ".github/workflows/shorebird_code_push_api_client.yaml"
      - "packages/shorebird_code_push_api_client/lib/**"
      - "packages/shorebird_code_push_api_client/test/**"
      - "packages/shorebird_code_push_api_client/pubspec.yaml"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/shorebird_code_push_api_client.yaml"
      - "packages/shorebird_code_push_api_client/lib/**"
      - "packages/shorebird_code_push_api_client/test/**"
      - "packages/shorebird_code_push_api_client/pubspec.yaml"

jobs:
  semantic-pull-request:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/semantic_pull_request.yml@v1

  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/dart_package.yml@v1
    with:
      working_directory: packages/shorebird_code_push_api_client

  pana:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/pana.yml@v1
    with:
      working_directory: packages/shorebird_code_push_api_client
